name: Read Power Platform Settings
author: Andersg
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  deploySettings: 
    description: The deploy settings
    required: false
    default: '{}'
  authSettings: 
    description: The auth settings
    required: false
    default: '{}'

runs:
  using: composite
  steps:
    - name: run
      shell: ${{ inputs.shell }}
      env:
        _deployToSettings: ${{ inputs.deploySettings }}
        _authContext: ${{ inputs.authSettings }}
      run: ${{ github.action_path }}/ReadDeploymentAndAuthSettings.ps1 -deployToSettings $ENV:_deployToSettings -authContext $ENV:_authContext

branding:
  icon: terminal
  color: blue
