name: Parse the Authentication context
author: Andersg
inputs:
  shell:
    description: Shell in which you want to run the action (powershell or pwsh)
    required: false
    default: powershell
  parentTelemetryScopeJson:
    description: Specifies the parent telemetry scope for the telemetry signal
    required: false
    default: '7b7d'
  envName: 
    description: The environment name
    required: false
    default: ''
  environment: 
    description: The environment name from the matrix?
    required: false
    default: ''
  projects: 
    description: The projects
    required: false
    default: '{}'

runs:
  using: composite
  steps:
    - name: run
      env:
        _envName: ${{ inputs.envName }}
        _environment: ${{ inputs.environment }}
        _projects: ${{ inputs.projects }}
      shell: ${{ inputs.shell }}
      run: ${{ github.action_path }}/ParseAuthContext.ps1 -envName $ENV:_envName -environment $ENV:_environment -projects $ENV:_projects

branding:
  icon: terminal
  color: blue
